#cloud-config

groups:
  - devs
  - bosses
users:
  - name: foobar
    gecos: Foo Bar. H
    groups: devs, bosses
    shell: /bin/dash
  - name: barfoo
    gecos: Bar Foo. I
    groups: devs
    shell: /bin/bash
