#cloud-config

runcmd:
  - echo hello
  - echo bye
groups:
  - devs
  - bosses
users:
  - name: foobar
    gecos: Foo Bar. H
    groups: devs, bosses
    shell: /bin/dash
    uid: 1004
  - name: barfoo
    gecos: Bar Foo. I
    groups: devs
    shell: /bin/bash
    uid: 1768
