#cloud-config

runcmd:
  - echo hello
  - echo bye

groups:
  - devs
  - bosses

users:
  - name: foobar
    gecos: Foo Bar. H
    groups: devs, bosses
    shell: /bin/dash
    uid: 1004
    homedir: /home/foobarhome
  - name: barfoo
    gecos: Bar Foo. I
    groups: devs
    shell: /bin/bash
    homedir: /home/barfoohome
    uid: 1768

write_files:
  - path: /etc/demo1.txt
    content: |
      Hello from demo1.txt,
      write_files test 1
    permissions: "0644"
    owner: root:root

  - path: /etc/demo2.conf
    content: |
      Hello from demo2.conf,
      write_files test 2
    permissions: "0755"
    owner: foobar:devs
